[package]
name = "mydm"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
egui = "0.30.0"
egui_extras = { version = "0.30.0", features = ["image"] }
env_logger = "0.11.6"
log = "0.4.25"
